-- DDL & dummy Data insert

-- 테이블 및 시퀀스 삭제
DROP TABLE PERSON;
DROP TABLE JOB;
DROP SEQUENCE PERSON_PNO_SQ;

-- 테이블 및 시퀀스 생성
CREATE TABLE JOB (
    jNO     NUMBER(2)    PRIMARY KEY,
    jNAME   VARCHAR2(30) NOT NULL UNIQUE
);
CREATE TABLE PERSON (
    pNO     NUMBER(5)       PRIMARY KEY,
    pNAME   VARCHAR2(30)    NOT NULL,
    jNO     NUMBER(2)       REFERENCES JOB(jNO) NOT NULL,
    KOR     NUMBER(3)       CHECK(KOR BETWEEN 0 AND 100),
    ENG     NUMBER(3)       CHECK(ENG BETWEEN 0 AND 100),
    MAT     NUMBER(3)       CHECK(MAT BETWEEN 0 AND 100)
);
CREATE SEQUENCE PERSON_PNO_SQ MAXVALUE 99999 NOCACHE NOCYCLE;
SELECT * FROM JOB;
SELECT * FROM PERSON;

-- DUMMY DATA
-- JOB TABLE (10, 배우) (20, 가수) (30, 엠씨)
INSERT INTO JOB VALUES (10, '배우');
INSERT INTO JOB VALUES (20, '가수');
INSERT INTO JOB VALUES (30, '엠씨');
-- PERSON TABLE (학번, 학생이름, 직업번호, 국어점수, 영어점수, 수학점수)
INSERT INTO PERSON VALUES (1, '정우성', 10, 90, 80, 81);
INSERT INTO PERSON VALUES (2, '박세영', 10, 80, 90, 80);
INSERT INTO PERSON VALUES (3, '배수지', 20, 20, 90, 90);
SELECT * FROM JOB;
SELECT * FROM PERSON;
